version: '3'
services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_USER: cinnamon
      POSTGRES_PASSWORD: cinnamon
      POSTGRES_DB: cinnamon
    ports:
      - '1234:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
volumes:
  database-data:
